### PR TITLE
worked on create blog and header component

### PR DESCRIPTION
**Pull request by Kingrapelli**
@SpringSrikanth @abhinay-developer worked on create blog and header components. please review and merge.

### CODE REVIEW

**Comment by abhinay-developer** [comment]
Form should be only one , also write method for forms and call on on init

**Comment by abhinay-developer** [comment]
Remove all inline stylings and convert to classes

**Comment by abhinay-developer** [comment]
Header component remove all nbsp; and add paddings using boostrap otherwise use classes

**Comment by mryenagandula** [comment]
@Kingrapelli please complete all the @abhinay-developer  comments and raise those changes with new PR. As of now am merging the PR.

**Pull request merged**
