### PR TITLE
added form inside the createblog

### PR DESCRIPTION
**Pull request by devarajthadaka**
@abhinay-developer @Kingrapelli @rajkumardusa @mryenagandula please review my pr

### CODE REVIEW

**Comment by abhinay-developer** [comment]
Create method for all form controls and call in ng oninit

**Comment by abhinay-developer** [comment]
All labels text first letter should be capital
For reset button remove type as submit

**Comment by mryenagandula** [comment]
@devarajthadaka please complete the @abhinay-developer changes and update the PR

**Comment by mryenagandula** [comment]
@devarajthadaka  Please complete your changes as soon as possible and raise a new PR. As of now am merging your PR.

**Pull request merged**
